# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on:
  push:
    branches: [master]
    
env:
  AZURE_WEBAPP_NAME: custom-card-game   # set this to your application's name
  CONTAINER_REGISTRY: ${{ secrets.REGISTRY_USERNAME }}.azurecr.io   # set secret with Container Registry name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: yarn install, build, and test
      run: |
        yarn install
        yarn build
    - name: ACR authentication
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}    
    - name: Docker Build & Push to ACR
      run: |
        docker build . -t ${{ env.CONTAINER_REGISTRY }}/card-game:${{ github.sha }}
        docker push ${{ env.CONTAINER_REGISTRY }}/card-game:${{ github.sha }}  
